// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_starter_app/test/features/main/presentation/cubit/app_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_starter_app/core/errors/failures.dart' as _i5;
import 'package:flutter_starter_app/core/usescases/usecases.dart' as _i7;
import 'package:flutter_starter_app/features/main/domain/entities/app_setting.dart'
    as _i8;
import 'package:flutter_starter_app/features/main/domain/entities/device.dart'
    as _i6;
import 'package:flutter_starter_app/features/main/domain/usecases/app_setting_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppSettingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingUseCase extends _i1.Mock implements _i3.AppSettingUseCase {
  MockAppSettingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Device>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Device>>.value(
            _FakeEither_0<_i5.Failure, _i6.Device>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Device>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i4.Stream<bool>>> getStreamConnectivity(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreamConnectivity,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i4.Stream<bool>>>.value(
                _FakeEither_0<_i5.Failure, _i4.Stream<bool>>(
          this,
          Invocation.method(
            #getStreamConnectivity,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i4.Stream<bool>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> getConnectivity(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConnectivity,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #getConnectivity,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.AppSetting>>> getSettings(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.AppSetting>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.AppSetting>>(
          this,
          Invocation.method(
            #getSettings,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.AppSetting>>>);
}
