name: Dart Lint

on:
  pull_request:
    branches:
      - main  # Change this to your main branch name
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  pubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Check version
        run: flutter --version
      - name: Check Install dependencies
        run: flutter pub get 
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.x'
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - name: Check version
        run: flutter --version
      - name: Analyze dart code
        run: flutter analyze